name: Deployment

on: [pull_request]
# implement on Merge

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: https://dreifuss-wysiwyg-editor.wepublish.dev/${{ GITHUB_REF##*/ }}
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build
        run: |
          yarn install
          lerna bootstrap
          lerna run build --stream
          lerna run build:deployment --stream
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_WEP_DEV }}
          service_account_key: ${{ secrets.GCP_SA_KEY_WEP_DEV }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: |
          gsutil cp ./packages/core/dist/index.html gs://dreifuss-wysiwyg-editor.wepublish.dev/${GITHUB_REF##*/}/index.html
          gsutil cp ./packages/core/dist/index_bundle.js gs://dreifuss-wysiwyg-editor.wepublish.dev/${GITHUB_REF##*/}/index_bundle.js
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://dreifuss-wysiwyg-editor.wepublish.dev/${GITHUB_REF##*/}
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://dreifuss-wysiwyg-editor.wepublish.dev/${GITHUB_REF##*/}
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
#      - name: Slack Notification
#        uses: rtCamp/action-slack-notify@master
#        env:
#          SLACK_CHANNEL: dev
#          SLACK_COLOR: '#3278BD'
#          SLACK_ICON: https://github.com/wepublish.png?size=48
#          SLACK_MESSAGE: 'We.Publish Deploy to Kubernetes done!'
#          SLACK_TITLE: 'CI/CD'
#          SLACK_USERNAME: 'Github (wepublish)'
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
