name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  remove_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_WEP_DEV }}
          service_account_key: ${{ secrets.GCP_SA_KEY_WEP_DEV }}
          export_default_credentials: true
      - name: Use gcloud CLI
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          gsutil rm -r gs://dreifuss-wysiwyg-editor.wepublish.dev/${BRANCH_NAME}
